#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

packages:
  - docker.io
  - unattended-upgrades

runcmd:
  - docker login parkanizeracr2024.azurecr.io -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker pull parkanizeracr2024.azurecr.io/grupa1/parkanizer-frontend:latest
  - docker run -p 80:80 parkanizeracr2024.azurecr.io/grupa1/parkanizer-frontend:latest  
final_message: "The system is finally up, after $UPTIME seconds"
