#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

packages:
  - docker.io
  - unattended-upgrades

write_files:
  - path: /home/adminuser/promtail-config-base64.yml
    content: |
      ${PROMTAIL_CONFIG}

runcmd:
  - cat /home/adminuser/promtail-config-base64.yml | base64 --decode > /home/adminuser/promtail-config.yml
  - docker login parkanizeracr2024.azurecr.io -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker pull parkanizeracr2024.azurecr.io/grupa1/parkanizer-frontend:latest
  - docker pull parkanizeracr2024.azurecr.io/monitoring/promtail:2.9.2
  - docker run --name=frontend -d -p 80:80 -p 443:443 parkanizeracr2024.azurecr.io/grupa1/parkanizer-frontend:latest
  - docker run -d --name=promtail -v /home/adminuser/promtail-config.yml:/etc/promtail/config.yml -v /var/lib/docker/containers:/var/lib/docker/containers -v /var/run/docker.sock:/var/run/docker.sock parkanizeracr2024.azurecr.io/monitoring/promtail:2.9.2 -config.file=/etc/promtail/config.yml
  
final_message: "The system is finally up, after $UPTIME seconds"
