#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

packages:
  - docker.io
  - unattended-upgrades

runcmd:
  - docker pull parkanizeracr2024.azurecr.io/grupa1/app:latest
  - docker run -d -p 8080:8080 parkanizeracr2024.azurecr.io/grupa1/app:latest

final_message: "The system is finally up, after $UPTIME seconds"
