#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

packages:
  - docker.io
  - unattended-upgrades



runcmd:
  - docker login parkanizeracr2024.azurecr.io -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker pull parkanizeracr2024.azurecr.io/grupa1/app:latest
  - docker pull parkanizeracr2024.azurecr.io/monitoring/promtail:2.9.2
  - docker run -d -p 80:8080 -e SPRING_DATASOURCE_URL=jdbc:postgresql://database.group1.azure.com:5432/parkingDb -e SPRING_DATASOURCE_USERNAME=username -e SPRING_DATASOURCE_PASSWORD=password parkanizeracr2024.azurecr.io/grupa1/app:latest
  # - docker run -d \
  #     -v /home/adminuser/promtail-config.yml:/etc/promtail/config.yml \
  #     -v /var/lib/docker/containers:/var/lib/docker/containers \
  #     -v /var/run/docker.sock:/var/run/docker.sock \
  #     parkanizeracr2024.azurecr.io/monitoring/promtail:2.9.2 \
  #     -config.file=/etc/promtail/config.yml

final_message: "The system is finally up, after $UPTIME seconds"
