#cloud-config

package_update: true
package_upgrade: true

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

packages:
  - docker.io
  - unattended-upgrades

runcmd:
  - docker login parkanizeracr2024.azurecr.io -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker pull parkanizeracr2024.azurecr.io/grupa1/app:latest
  - docker run -d -p 8080:8080 -e SPRING_DATASOURCE_URL=jdbc:postgresql://jk-example-postgresql-server.postgres.database.azure.com:5432/parkingDb -e SPRING_DATASOURCE_USERNAME=username -e SPRING_DATASOURCE_PASSWORD=password parkanizeracr2024.azurecr.io/grupa1/app:latest
final_message: "The system is finally up, after $UPTIME seconds"
